name: Bundle and Push

on:
    push:
        branches:
            - dev

# 为整个 jobs 提供 write contents 的权限
permissions:
    contents: write

jobs:
    bundle:
        runs-on: ubuntu-latest
        steps:
            # 获取仓库内容
            - name: Checkout
              uses: actions/checkout@v3
            # 安装 nodejs
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21
            # 允许打包脚本
            - name: Run bundle script
              run: node bundle.js
            # 将打包后的 dist 分支发布到 dist 分支
            - name: Push dist branch
              run: |
                  git config user.name github-action
                  git config user.email github-action@github.com
                  git checkout -b dist
                  git add -f dist/
                  git commit -m "github action auto push"
                  git push -f origin dist

            # 核心在这里，在仓库的 Settings -> Environments -> New environment
            # 中新建一个环境变量，名为 PUSH_KEY
              env:
                  github_token: ${{ secrets.PUSH_KEY }}
