name: Bundle and Push

on:
  push:
    branches:
      - dev

jobs:
  bundle:
    runs-on: ubuntu-latest
    permissions: # PUSH 权限要求
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Hydrogen'
      - name: Run bundle script to generate dist folder
        run: node bundle.js
      - name: only remain files that in dist folder and push to dist branch
        run: |
          git config user.name github-action
          git config user.email github-action@github.com
      - run: ls -al
      - run: git rm *
      - run: ls -al
      - run: mv dist/* .
      - run: ls -al
      - run: |
          git add .
          git commit -m "github action auto push"
          git branch
          git checkout -b dist
          git push -f origin dist
        env: # PUSH 权限要求
          github_token: ${{ secrets.PUSH_KEY }}
