name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

permissions:
  contents: write

on:
  push:
    branches: main

jobs:

  move-page-content-to-page-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/page'

      - name: Set Git User Info
        run: |
          git config user.email "linhieng@qq.com"
          git config user.name "linhieng"

      - name: test
        run: |

          echo "test" > a.txt
          git add .
          git commit -m "deploy"
          git push

