name: move folder to branch
run-name: ${{ github.actor }} test move folder to branch

permissions:
  contents: write

on:
  push:
    branches: main

jobs:

  move-page-content-to-page-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/page'

      - name: Set Git User Info
        run: |
          git config user.email "linhieng@qq.com"
          git config user.name "linhieng"

      - name: clear branch contnet
        run: |
          git rm -rf .

      - name: fetch content
        run: |
          git fetch origin main:tmp
          git checkout tmp -- dist
          mv dist/* .

      - name: add -> commit -> push
        run: |
          git add .
          git commit -m "deploy"
          git push

      - name: debug
        run: |
          git remote -v
          git branch
